force-app/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Item__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <inlineHelpText>Valor obtenido automáticamente, no se requiere entrada manual.</inlineHelpText>
    <label>Discount (Amount)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <inlineHelpText>Valor obtenido automáticamente, no se requiere entrada manual.</inlineHelpText>
    <label>Discount (Percentage)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order.</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El Producto debe estar activado antes de usarlo. Porfavor, active el Producto checkeando su campo &apos;Activo&apos;</errorMessage>
        <filterItems>
            <field>Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <formula>IF(
	AND(
		ISBLANK(Discount_Amount__c),
		ISBLANK(Discount_Percentage__c)
	),
	Quantity__c *  Unit_Price__c,
	IF(
		NOT(ISBLANK(Discount_Percentage__c)),
		CEILING((Quantity__c *  Unit_Price__c) - ((Quantity__c *  Unit_Price__c) * Discount_Percentage__c)),
		IF(
			NOT(ISBLANK(Discount_Amount__c)),
			(Quantity__c * Unit_Price__c) - Discount_Amount__c,
			Quantity__c *  Unit_Price__c
		)
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <inlineHelpText>Valor calculado automáticamente, no hace falta la entrada manual.</inlineHelpText>
    <label>Unit Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order.</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total to Pay</label>
    <summarizedField>Invoice_Item__c.Sub_Total__c</summarizedField>
    <summaryForeignKey>Invoice_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product.</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount (Amount)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <label>Discount (Percentage)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PrintOrderWithItemsController.cls
public without sharing class PrintOrderWithItemsController {
    public Order__c order {get; set;}
	public Id orderId {get; set;}
	public List<Invoice_Item__c> invoiceItems {get; set;}

	public PrintOrderWithItemsController() {
		
		this.orderId = ApexPages.currentPage().getParameters().get('id');

		this.invoiceItems = new List<Invoice_Item__c>();
		
		this.order = [
			SELECT 
			Id,
			OwnerId,
			IsDeleted,
			Name,
			CreatedDate,
			CreatedById,
			LastModifiedDate,
			LastModifiedById,
			SystemModstamp,
			LastActivityDate,
			LastViewedDate,
			LastReferencedDate,
			Total__c
			FROM Order__c 
			WHERE Id = :orderId
		];

		this.invoiceItems = [
			SELECT 
			Id,
			IsDeleted,
			Name,
			CreatedDate,
			CreatedById,
			LastModifiedDate,
			LastModifiedById,
			SystemModstamp,
			LastActivityDate,
			LastViewedDate,
			LastReferencedDate,
			Quantity__c,
			Unit_Price__c,
			Discount_Amount__c,
			Product__c,
			Order__c,
			Product_Name__c,
			Sub_Total__c,
			Discount_Percentage__c
			FROM Invoice_Item__c 
			WHERE Order__c = :orderId
		];

	}
}